const PDFDocument = require('pdfkit');

module.exports = function generateInvoiceBuffer({ user, hotel, bookingCode, rooms, checkInDate, checkOutDate }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument();
    const buffers = [];

    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => resolve(Buffer.concat(buffers)));

    const formatDate = d => new Date(d).toLocaleDateString('en-GB', {
      day: '2-digit', month: 'short', year: 'numeric'
    });

    const formatNaira = n => `₦${Number(n).toLocaleString('en-NG')}`;

    doc.fontSize(20).text('🏨 Booking Invoice', { align: 'center' }).moveDown();
    doc.fontSize(14).text(`Booking Code: ${bookingCode}`);
    doc.text(`Guest: ${user.name} (${user.email})`);
    doc.text(`Hotel: ${hotel.name}`);
    doc.text(`Check-in: ${formatDate(checkInDate)}`);
    doc.text(`Check-out: ${formatDate(checkOutDate)}`);
    doc.moveDown();

    rooms.forEach((room, i) => {
      doc.text(`${i + 1}. Room: ${room.name || room._id} – ${formatNaira(room.price)}`);
    });

    const total = rooms.reduce((sum, r) => sum + r.price, 0);
    doc.moveDown().font('Helvetica-Bold').text(`Total: ${formatNaira(total)}`);
    doc.moveDown(2).fontSize(10).fillColor('gray')
       .text('Generated by E-Hotel Booking System', { align: 'center' });

    doc.end();
  });
};
